title: Pawel Trela | Ruby on Rails Developer
description:
url: https://ptrela.pl
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
